version: 1.0.{build}
clone_depth: 5
force_https_clone: true
environment:
  REPO_CLONE_ATTEMPTS: 5
  REPO_CLONE_TIMEOUT: 180
  REPO_CLONE_PROTOCOL: https
  buildconfig: Release
  matrix:
  - test_type: Unit.Testing
    test_assemblies: Serilog.Sinks.Async.UnitTests\bin\$env:buildconfig\Serilog.Sinks.Async.UnitTests.dll
    test_category: Unit
    test_settings:
  - test_type: Integration.Testing
    test_assemblies: Serilog.Sinks.Async.IntTests\bin\$env:buildconfig\Serilog.Sinks.Async.IntTests.dll
    test_category: Integration
    test_settings:
  - test_type: Perf.Testing
    test_assemblies: Serilog.Sinks.Async.IntTests\bin\$env:buildconfig\Serilog.Sinks.Async.IntTests.dll
    test_category: Integration.Perf
    test_settings:
matrix:
    fast_finish: false
init:
#- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
clone_script:
- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/clone-repo-retry.ps1'))
build_script:
- cd src
- msbuild.exe Serilog.Sinks.Async.sln /t:Rebuild /p:Configuration=%buildconfig% /verbosity:minimal
- cd..
after_build:
- cd src
- cd Serilog.Sinks.Async
- ..\.nuget\nuget.exe pack Serilog.Sinks.Async.csproj -Symbols -IncludeReferencedProjects -Properties Configuration=%buildconfig%
- cd..
- cd..
- appveyor PushArtifact src\Serilog.Sinks.Async\Serilog.Sinks.Async.1.0.0.nupkg
- appveyor PushArtifact src\Serilog.Sinks.Async\Serilog.Sinks.Async.1.0.0.symbols.nupkg
test_script:
- ps: >-
    cd src

    $env:test_assemblies.Split(';') | % {
      $assemblyName = $ExecutionContext.InvokeCommand.ExpandString($_)

      if ($env:test_settings){
        &vstest.console $assemblyName /InIsolation /logger:AppVeyor /settings:$env:test_settings /testcasefilter:`"TestCategory=$env:test_category`"
        } else {
        &vstest.console $assemblyName /InIsolation /logger:AppVeyor /testcasefilter:`"TestCategory=$env:test_category`"
        }

      if ($global:LASTEXITCODE -ne 0){
        $host.SetShouldExit($global:LASTEXITCODE)
        break
      }
    }

    cd..
deploy:
  provider: NuGet
  api_key:
    secure: ouXO+JncruHh/QCmfUIrxaho6E8wocItwEWxePF9uziuEWe0jruLGyuFxzcoUKy3
  skip_symbols: false
